### ISSUE TITLE
Extract shard ID from /events/finalized notifier event

### ISSUE THREAD

**Issue by elrondex** [multiversx/mx-chain-notifier-go#22]
I enabled EventNotifierConnector.Enabled = true in observer node and observer start to push events like:

POST /events/finalized HTTP/1.1
Host: localhost:5000
User-Agent: Go-http-client/1.1
Content-Length: 75
Content-Type: application/json
Accept-Encoding: gzip

{"hash":"94e75f10d8b598b516a5c84a52a2fa0c404006da94433d5b3abe8379f286e0d5"}

Looks great!
Now to have full Blockchain events each shard observer will push events like that:

{"hash":"x"}
{"hash":"y"}
{"hash":"z"}

My question is how to know if "hash":"x" belongs to shard 0,1 or 2?
Do we have shard number encoded in the hash value?
Can I extract shard number from "hash":"94e75f10d8b598b516a5c84a52a2fa0c404006da94433d5b3abe8379f286e0d5" ?
I'm not sure but I don't think so ...

Now to solve my problem I can setup one ./event-notifier instance for each observer node
[obs0] -> push to -> 5000
[obs1] -> push to -> 5001
[obs2] -> push to -> 5002

This looks ok, but I prefer to have only one ./event-notifier instance.

I wonder if it's possible to push this event in this form:
{"hash":"94e75f10d8b598b516a5c84a52a2fa0c404006da94433d5b3abe8379f286e0d5", "shard": 1}
Is it viable? 

I can have a direction, to see how I can adapt my design for my Elrondex library?
Long run I need to extract events from Elrond Blockchain, as fast as I can, in order to 
review, analize and publish these events to smart consumers over websokets (inclusive web browsers) 

Thanks!
@elrondex

**Comment by mateigraura** [comment]
The current websocket dispatcher does not support what you're referring to, but if you'd use the notifier as a rabbitMQ dispatcher, you'd get 3 types of events:
- event logs
- finalized block events
- revert block events

The first type of event contains the headerHash and a list of event payloads. Upon receiving this, you can wait for the finalized block event to confirm the events received previously.

This requires setting up a rabbitmq instance and using the following config section: [here](https://github.com/ElrondNetwork/notifier-go/blob/main/config/config.toml#L35-L50).  Also, you should be running the notifier with the following flag to enable the rabbitMQ publisher: `./event-notifier --api-type rabbit-api`

**Comment by schimih** [comment]
This issue has been inactive for some time and a solution has already been suggested. If the problem still persists, we kindly ask that you open a new issue or join our Discord channel for further assistance.
https://discord.gg/multiversxbuilders
